### ISSUE TITLE
RequestError: TransportError elasticsearch 

### ISSUE THREAD

**Issue by barhaterahul** [AndroidHooker/hooker#8]
I have followd the step given in readme,

I am getting this error.
My machine is Ubutnu 64bit.
I am using latest hooker version.

Error :   -------------------------------------------------------------------------------------------------
[MainProcess/MainThread/DEBUG] 239: Traceback (most recent call last):
  File "hooker_xp.py", line 70, in <module>
    main()
  File "hooker_xp.py", line 53, in main
    analysis = ManualAnalysis(commandLineParser)
  File "/home/mobisec/Downloads/hooker-master/hooker_xp/hooker_xp/ManualAnalysis.py", line 51, in **init**
    super(ManualAnalysis, self).**init**(MainConfiguration.build(commandLineParser), ReportingConfiguration.build(commandLineParser), )
  File "/home/mobisec/Downloads/hooker-master/hooker_xp/hooker_xp/analysis/Analysis.py", line 53, in **init**
    self.reporter = Reporter(self.reportingConfiguration)
  File "/home/mobisec/Downloads/hooker-master/hooker_xp/hooker_xp/report/Reporter.py", line 51, in **init**
    self.**initializeReporters()
  File "/home/mobisec/Downloads/hooker-master/hooker_xp/hooker_xp/report/Reporter.py", line 110, in __initializeReporters
    self.es = Es([{"host":self.reportingConfiguration.elasticsearchIp, 'port':self.reportingConfiguration.elasticsearchPort}])
  File "build/bdist.linux-x86_64/egg/hooker_common/elasticsearch/Es.py", line 57, in __init**
    self.__initializeConnection()
  File "build/bdist.linux-x86_64/egg/hooker_common/elasticsearch/Es.py", line 369, in __initializeConnection
    self.__createHookerIndex()
  File "build/bdist.linux-x86_64/egg/hooker_common/elasticsearch/Es.py", line 389, in __createHookerIndex
    self.esInstance.indices.create(index=Es.ES_INDEX_NAME_HOOKER, body=Es.__getBodyIndex())
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 102, in create
    params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception')

androidTemporaryPath=/tmp/android/
# Path to androguard framework

androguardPath=/opt/mobisec/Android/androguard
# type of device (real or emulated)

device=emulated
# 
# Analysis Configuration
# 

[analysis]
# type of the analysis (manual or automatic)

type=automatic
# name of the analysis

name=Sample Automatic Analysis
# directory in which APKs

apks=../tools/sampleApps/
# number of emulators
# in manual mode, only a single emulator is used
# in automatic mode, one APK = one Emulator

maxNumberOfEmulators=2
# applications to install and execute before starting the experiment
# [application filename MUST equals their main activity name]

prepareApks=../tools/APK-contactGenerator/com.amossys.hooker.generatecontacts.ImportContacts.apk
# scenario
# IMPORTANT: In your scenario, you cannot have a stimulate action separated from an execute action

scenario=execute,stimulate,reboot,execute,stimulate,externalStimulation
# output directory

outputdirectory=/tmp/outdir/
# 
# Reporting Configuration
# 

[reporting]
# activate or not the reporting of events in an elasticsearch database

elasticsearch_mode=true
# if elasticsearch activated, specify the ES IP address

elasticsearch_ip=127.0.0.1
# if elasticsearch activated, specify the ES IP port number

elasticsearch_port=9200
# elasticsearch index

elasticsearch_index=hooker_test
# elasticsearch doctype for events

elasticsearch_doctype=event
# activate or not the creation of a text report containing all the captured events

**Comment by Tibap** [comment]
Hi barhaterahul,
Which version of ElasticSearch do you have? Can you give us more details on your setup environment?
